const actionType = {
    GET_ALLHOME: 'GET_ALLHOME',
    GET_ALLCITIES: 'GET_ALLCITIES',
    GET_HOMESBYCITYNAME: 'GET_HOMESBYCITYNAME',
    GET_HOTELBYID: 'GET_HOTELBYID',
    GET_ROOMSBYIDHOTEL: 'GET_ROOMSBYIDHOTEL',
    GET_TYPEROOMS: 'GET_TYPEROOMS',
    GET_ROOMBYID: 'GET_ROOMBYID',
    POST_CREATENEWBOOKING: 'POST_CREATENEWBOOKING',
    GET_MYBOOKINGSBYEMAIL: 'GET_MYBOOKINGSBYEMAIL',
    PUT_BOOKINGSUCCESS: 'PUT_BOOKINGSUCCESS',
    GET_CANCELBOOKING: 'GET_CANCELBOOKING',
    SEARCH_HOMES: 'SEARCH_HOMES',
    POST_CREATEHOTEL: 'POST_CREATEHOTEL',
    DELETE_HOTEL: 'DELETE_HOTEL',
    UPDATE_HOME: 'UPDATE_HOME'
}
export default actionType